In [1]:
# TF-IDF

In [2]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [34]:
text = [
    'Apple is launching new iphone in July.',
    'Motorola is launching new Edge in July.',
    'Amazon is launching a new platform  in July.'
    'I will leave in July.',
    'I am eating chocolates.',
    'I am eating Biryani and you are eating rice.'
]

In [44]:
text = [
    'I am happy',
    'I am sad',
    'I feel good',
    'This is terrible and sad',
    'This is worse'
]

In [45]:
v = TfidfVectorizer()

In [46]:
v.fit(text)

TfidfVectorizer()

In [47]:
trnsformed_op = v.transform(text)

In [48]:
trnsformed_op

<5x10 sparse matrix of type '<class 'numpy.float64'>'
	with 14 stored elements in Compressed Sparse Row format>

In [49]:
print(v.vocabulary_)

{'am': 0, 'happy': 4, 'sad': 6, 'feel': 2, 'good': 3, 'this': 8, 'is': 5, 'terrible': 7, 'and': 1, 'worse': 9}


In [50]:
f = v.get_feature_names_out()

In [51]:
for i in f:
    idx = v.vocabulary_.get(i)
    # print(idx)
    idf_score = v.idf_[idx]
    print(f'{i} : {idf_score}')

am : 1.6931471805599454
and : 2.09861228866811
feel : 2.09861228866811
good : 2.09861228866811
happy : 2.09861228866811
is : 1.6931471805599454
sad : 1.6931471805599454
terrible : 2.09861228866811
this : 1.6931471805599454
worse : 2.09861228866811


In [53]:
trnsformed_op.toarray()

array([[0.62791376, 0.        , 0.        , 0.        , 0.77828292,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.70710678, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.70710678, 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.70710678, 0.70710678, 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.50297966, 0.        , 0.        , 0.        ,
        0.40580082, 0.40580082, 0.50297966, 0.40580082, 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.53177225, 0.        , 0.        , 0.53177225, 0.659118  ]])

In [54]:
import pandas as pd
df = pd.read_csv('Ecommerce_data.csv')

In [56]:
df.shape

(24000, 2)

In [57]:
df['label'].value_counts()

label
Household                 6000
Electronics               6000
Clothing & Accessories    6000
Books                     6000
Name: count, dtype: int64

In [58]:
df['Labels'] = df['label'].map({
    'Household' : 0,
    'Electronics' : 1,
    'Clothing & Accessories' : 2,
    'Books' : 3
})

In [61]:
df.head(1)

Text      label  Labels
0  Urban Ladder Eisner Low Back Study-Office Comp...  Household       0

In [60]:
from sklearn.model_selection import train_test_split

In [82]:
x_train, x_test, y_train, y_test = train_test_split(
    df.Text,
    df.Labels
)

In [63]:
x_train.shape

(18000,)

In [65]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import Pipeline
from sklearn.metrics import classification_report

In [66]:
model = Pipeline([
    ('vectorizer', TfidfVectorizer()),
    ('Model',  MultinomialNB())
])

In [67]:
model.fit(x_train, y_train)

Pipeline(steps=[('vectorizer', TfidfVectorizer()), ('Model', MultinomialNB())])

In [69]:
y_pred = model.predict(x_test)

In [70]:
classification_report(y_test, y_pred)

'              precision    recall  f1-score   support\n\n           0       0.93      0.97      0.95      1547\n           1       0.97      0.97      0.97      1438\n           2       0.97      0.98      0.98      1507\n           3       0.98      0.93      0.95      1508\n\n    accuracy                           0.96      6000\n   macro avg       0.96      0.96      0.96      6000\nweighted avg       0.96      0.96      0.96      6000\n'

In [71]:
x_test.head(1)

11681    Rani Saahiba Women's Net Dupatta Look your Eth...
Name: Text, dtype: object

In [76]:
test = ['I was expecting camel brown, as shown in the photograph, because I used this same sandal for 7 years.', 'Great value for money. Extended battery life.']

In [77]:
model.predict(test)

array([0, 1])

In [78]:
from sklearn.ensemble import RandomForestClassifier

In [79]:
pipe = Pipeline([
    ('vect', TfidfVectorizer()),
    ('Model' , RandomForestClassifier())
])

In [83]:
pipe.fit(x_train, y_train)

Pipeline(steps=[('vect', TfidfVectorizer()),
                ('Model', RandomForestClassifier())])

In [84]:
pipe.predict(test)

array([3, 3])