## LLMs

In [1]:
import spacy

!python -m spacy download en_core_web_lg

In [7]:
nlp = spacy.load('en_core_web_lg')

In [33]:
doc = nlp('glass mouse nashit')

In [34]:
for token in doc:
    print(token.text, " | ", token.has_vector)

glass  |  True
mouse  |  True
nashit  |  False


In [38]:
doc[2].vector

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.

In [42]:
doc[1].vector.shape

(300,)

In [39]:
token_i = nlp('komal')

In [41]:
token_i.vector.shape

(300,)

In [43]:
token_i = nlp('k')

In [44]:
token_i.vector.shape

(300,)

In [47]:
token_b = nlp('go')

In [49]:
doc = nlp('go gone went going goes hello komal')

In [53]:
for token in doc:
    print(f'{token.text} | {token_b.text} |', token.similarity(token_b))

go | go | 1.0
gone | go | 0.7206540107727051
went | go | 0.6645714640617371
going | go | 0.863892138004303
goes | go | 0.6878067851066589
hello | go | 0.38605427742004395
komal | go | -0.15756677091121674


In [54]:
def print_similarity(word_b, word_c):
    token_b = nlp(word_b)
    doc = nlp(word_c)
    for token in doc:
        print(f'{token.text} | {token_b.text} |', token.similarity(token_b))

In [55]:
print_similarity('bread', 'bread sandwich butter naan wheat glass')

bread | bread | 1.0
sandwich | bread | 0.6874560117721558
butter | bread | 0.7272146940231323
naan | bread | 0.4963163435459137
wheat | bread | 0.6572456359863281
glass | bread | 0.31061556935310364


In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('Fake_Real_Data.csv')

In [4]:
df.head(1)

Text label
0   Top Trump Surrogate BRUTALLY Stabs Him In The...  Fake

In [5]:
df.shape

(9900, 2)

In [6]:
df.isna().sum()

Text     0
label    0
dtype: int64

In [7]:
df.duplicated().sum()

np.int64(35)

In [8]:
df.drop_duplicates(inplace = True)

In [9]:
df['label'].value_counts()

label
Fake    5000
Real    4865
Name: count, dtype: int64

In [10]:
df['Label'] = df['label'].map({'Fake':0, 'Real':1})

In [11]:
df.head(5)

Text label  Label
0   Top Trump Surrogate BRUTALLY Stabs Him In The...  Fake      0
1  U.S. conservative leader optimistic of common ...  Real      1
2  Trump proposes U.S. tax overhaul, stirs concer...  Real      1
3   Court Forces Ohio To Allow Millions Of Illega...  Fake      0
4  Democrats say Trump agrees to work on immigrat...  Real      1

In [12]:
nlp = spacy.load('en_core_web_lg')

In [13]:
df['vector'] = df['Text'].apply(lambda text: nlp(text).vector)

In [14]:
df.head(1)

Text label  Label  \
0   Top Trump Surrogate BRUTALLY Stabs Him In The...  Fake      0   

                                              vector  
0  [-0.103623025, 0.17802684, -0.11873861, -0.034...

In [15]:
from sklearn.model_selection import train_test_split

In [16]:
x_train, x_test, y_train, y_test = train_test_split(df.vector.values, df.Label)

In [17]:
import numpy as np
x_train_2d = np.stack(x_train)
x_test_2d = np.stack(x_test)

In [18]:
a = np.array([5,6,7])
b = np.array([11,12,13])

In [19]:
np.stack((a,b))

array([[ 5,  6,  7],
       [11, 12, 13]])

In [20]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.preprocessing import MinMaxScaler

In [21]:
scaler = MinMaxScaler()

In [22]:
x_train_s = scaler.fit_transform(x_train_2d)
x_test_s = scaler.fit_transform(x_test_2d)

In [23]:
model = MultinomialNB()

In [24]:
model.fit(x_train_s, y_train)

MultinomialNB()

In [25]:
model.predict(x_test_s)

array([1, 0, 0, ..., 0, 0, 1])

In [26]:
user = input('enter news')
vec = nlp(user).vector
v = vec.reshape(1, -1)
x = model.predict(v)
if x == 1:
    print('Real News')
else:
    print('Fake News')

enter news as


Fake News


In [30]:
import pickle


In [31]:
with open("data.pkl", "wb") as file:
    # Serialize and save the data
    pickle.dump(model, file)

#RNN 

In [49]:
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense

In [50]:
df = pd.read_csv('Fake_Real_data.csv')

In [51]:
df.head(1)

Text label
0   Top Trump Surrogate BRUTALLY Stabs Him In The...  Fake

In [52]:
tokenizer = Tokenizer(num_words=5000)

In [53]:
tokenizer.fit_on_texts(df['Text'])

In [54]:
sequences = tokenizer.texts_to_sequences(df['Text'])

In [55]:
df['Label'] = df['label'].map({'Fake':0, 'Real':1})

In [56]:
x = pad_sequences(sequences, maxlen = 300)

In [57]:
y = np.array(df['Label'])

In [58]:
model = Sequential([
    Embedding(input_dim = 5000, output_dim=128, input_length=300),
    LSTM(64, return_sequences= True),
    LSTM(32),
    Dense(1, activation = 'sigmoid')
])

C:\Users\s_nas\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [59]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [60]:
model.fit(x, y, epochs=10)

Epoch 1/10
310/310 ━━━━━━━━━━━━━━━━━━━━ 71s 210ms/step - accuracy: 0.9755 - loss: 0.1479
Epoch 2/10
310/310 ━━━━━━━━━━━━━━━━━━━━ 67s 217ms/step - accuracy: 0.9998 - loss: 0.0022
Epoch 3/10
310/310 ━━━━━━━━━━━━━━━━━━━━ 67s 216ms/step - accuracy: 1.0000 - loss: 3.4545e-04
Epoch 4/10
310/310 ━━━━━━━━━━━━━━━━━━━━ 67s 215ms/step - accuracy: 0.9967 - loss: 0.0102
Epoch 5/10
310/310 ━━━━━━━━━━━━━━━━━━━━ 67s 217ms/step - accuracy: 0.9999 - loss: 7.2728e-04
Epoch 6/10
310/310 ━━━━━━━━━━━━━━━━━━━━ 68s 219ms/step - accuracy: 1.0000 - loss: 7.3442e-05
Epoch 7/10
310/310 ━━━━━━━━━━━━━━━━━━━━ 68s 218ms/step - accuracy: 1.0000 - loss: 4.3753e-05
Epoch 8/10
310/310 ━━━━━━━━━━━━━━━━━━━━ 67s 216ms/step - accuracy: 1.0000 - loss: 3.0655e-05
Epoch 9/10
310/310 ━━━━━━━━━━━━━━━━━━━━ 67s 217ms/step - accuracy: 1.0000 - loss: 2.3795e-05
Epoch 10/10
310/310 ━━━━━━━━━━━━━━━━━━━━ 72s 231ms/step - accuracy: 1.0000 - loss: 1.8553e-05


In [69]:
# nlp = spacy.load('en_core_web_sm')
def classify(article):
    sequence = tokenizer.texts_to_sequences([article])
    padded_seq = pad_sequences(sequence, maxlen = 300)
    pred =model.predict(padded_seq)[0][0]
    return 'REAL' if pred > 0.5 else 'FAKE'

In [72]:
article = '''With all votes counted, right-wing historian Karol Nawrocki has been elected Poland's new president, the state electoral commission (PKW) said.

PKW said Nawrocki won 50.9% percent of the votes – ahead of Warsaw's liberal mayor Rafal Trzaskowski on 49.1% percent.'''

In [73]:
classify(article)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step


'REAL'